services:
  airflow:
    image: airflow-custom
    container_name: airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "bbbrBkReEtApiLEKAlhtrTP6eylT32tvg_KyK3tLqco="
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "minio_conn"  # Nome da conexão para o MinIO no Airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scraping:/opt/airflow/dags/scraping
    ports:
      - "8081:8080"
    networks:
      - airflow_net
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # Porta da API
      - "9001:9001"  # Porta fixa para a Web UI
    volumes:
      - minio-data:/data
    networks:
      - airflow_net

  spark:
    image: bitnami/spark
    container_name: spark
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
    networks:
      - airflow_net

networks:
  airflow_net:

volumes:
  minio-data:
  airflow_db:
  airflow-dags:
  airflow-logs:
  airflow-plugins:
