services:
  airflow:
    image: apache/airflow:2.4.2
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./Scraping:/opt/airflow/dags/Scraping
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: ["bash", "-c", "airflow db init && airflow webserver"]
    networks:
      - etl_network
    depends_on:
      - minio
      - pyspark
    restart: always

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio_data:/data
    networks:
      - etl_network
    restart: always

  pyspark:
    image: apache/spark:3.5.0
    environment:
      - SPARK_MODE=standalone
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "7077:7077"
      - "8081:8081"
    networks:
      - etl_network
    restart: always

networks:
  etl_network:
    driver: bridge
